### ISSUE TITLE
bash: letsencrypt-vesta: command not found

### ISSUE THREAD

**Issue by smmalloy** [interbrite/letsencrypt-vesta#1]
Hello, Firstly thanks for creating this. I followed the installation steps, but receive the following error when I run `letsencrypt-vesta USERNAME DOMAIN
bash: letsencrypt-vesta: command not found`

Any ideas?

**Comment by jpitoniak** [comment]
Three possibilities:
1. You didn't properly symlink the lets-encrypt vesta command in /usr/local/bin (do an "ls -la /usr/local/bin" to check).
2. /usr/local/bin isn't in your PATH environment variable.  I tested on a fresh install of CentOS, where it appears to be set by default, but other distros may vary.
3. For some reason the letsencrypt-vesta script didn't check out with execute permissions ("chmod 755 /usr/local/letsencrypt-vesta/letsencrypt-vesta" should fix that).

My guess is that #2 is most likely the case.  Good luck.

**Comment by jpitoniak** [comment]
Sorry, turns out there was a typo in my instructions (someone else just submitted a pull request with the fix).  The correct command to do the symlink is:

```
ln -s /usr/local/letsencrypt-vesta/letsencrypt-vesta /usr/local/bin/letsencrypt-vesta
```

**Comment by smmalloy** [comment]
Indeed it works! Thanks!
