### ISSUE TITLE
Let's encrypt returned an error status. Aborting. (SOLVED)

### ISSUE THREAD

**Issue by djsigfried56** [interbrite/letsencrypt-vesta#15]
Hi

So installed letsencrypt-vesta it worked on my local server but when I try to install it on my VPS I get this:

`root@vps258991:~# letsencrypt-vesta admin yanobite.eu
/usr/local/vesta/bin/v-list-web-domains-alias: line 19: /func/main.sh: No such file or directory
/usr/local/vesta/bin/v-list-web-domains-alias: line 26: check_args: command not found
/usr/local/vesta/bin/v-list-web-domains-alias: line 27: validate_format: command not found
/usr/local/vesta/bin/v-list-web-domains-alias: line 28: is_object_valid: command not found
/usr/local/vesta/bin/v-list-web-domains-alias: line 45: shell_list: command not found
/usr/local/vesta/bin/v-get-user-value: line 17: /func/main.sh: No such file or directory
/usr/local/vesta/bin/v-get-user-value: line 24: check_args: command not found
/usr/local/vesta/bin/v-get-user-value: line 25: validate_format: command not found
/usr/local/vesta/bin/v-get-user-value: line 26: is_object_valid: command not found
/usr/local/vesta/bin/v-get-user-value: line 34: get_user_value: command not found
Checking for new version...
Requesting root privileges to run letsencrypt...
   /root/.local/share/letsencrypt/bin/letsencrypt -t --renew-by-default --agree-tos --webroot -w /etc/letsencrypt/webroot --server https://acme-v01.api.letsencrypt.org/directory -m -d yanobite.eu certonly
usage:
  letsencrypt-auto [SUBCOMMAND] [options] [-d domain] [-d domain] ...

The Let's Encrypt agent can obtain and install HTTPS/TLS/SSL certificates.  By
default, it will attempt to use a webserver both for obtaining and installing
the cert. Major SUBCOMMANDS are:

  (default) run        Obtain & install a cert in your current webserver
  certonly             Obtain cert, but do not install it (aka "auth")
  install              Install a previously obtained cert in a server
  renew                Renew previously obtained certs that are near expiry
  revoke               Revoke a previously obtained certificate
  rollback             Rollback server configuration changes made during install
  config_changes       Show changes made to server config during installation
  plugins              Display information about installed plugins
letsencrypt: error: argument -m/--email: expected one argument
Let's encrypt returned an error status.  Aborting.
`
I did following the installation guide. It looks like it's a vesta cp error. Does someone know how to resolve this issue? Or what I should do next?
Thanks
Me

**Comment by djsigfried56** [comment]
Removing everything of Lets Encrypt en Lets Encrypt vesta and then reinstalling solved the problem.

**Comment by stilet** [comment]
No, this does not help

**Comment by openKadi** [comment]
before running let's encrypt, I assume your are using Lets Encrypt vesta right? run the following command:
`export VESTA=/usr/local/vesta/`
then run
`letsencrypt-vesta -m YOUR_EMAIL -u YOUR_USERNAME YOUR_DOMAINE`

**Comment by jpitoniak** [comment]
Also be sure you are running as root, either from a root shell or by using "sudo" in front of the letsencrypt-vesta command.  You won't be able to make any of the config changes unless you have superuser privs.

**Comment by ganganimaulik** [comment]
I also had similar problem on centOs 7.

`export VESTA=/usr/local/vesta/` this just works like a charm :+1: 

Thank You openKadi.
