### ISSUE TITLE
>10 domains per certificate issue

### ISSUE THREAD

**Issue by snakehill** [interbrite/letsencrypt-vesta#25]
When trying to combine a good number of domains in one certificate, it leads to the following error message:
`letsencrypt: error: unrecognized arguments: [domains]
Let's encrypt returned an error status.  Aborting.`

This seems to happen whenener trying to obtain a certificate to more than 10 domains, whereas Let's Encrypt supports, I believe, up to 100 domains per certificate.

Splitting up the related domains over multiple certificates works fine.

**Comment by jpitoniak** [comment]
When you see "Let's encrypt returned an error status. Aborting." this means that something went wrong in the ACME client--either something in that program didn't work or Let's Encrypt rejected the rejected the request for some reason.  When this happens, you should probably bring up this issue on the Let's Encrypt support forums, as it's not something I can likely address in letsencrypt-vesta.

This being said, were you trying to request a certificate for any country-code TLDs or other uncommon TLDs by chance?  I've seen reports of Let's Encrypt tripping up on certain TLDs, though I haven't been actively following the issue as I haven't run into it myself.

**Comment by snakehill** [comment]
Nope, did that just with .com domains. Tried adding 12 domains to a single cert, didn't work. Split it up into two certs exactly the same way and that worked fine. Just is a little inconvenient though.

**Comment by jpitoniak** [comment]
Hmmm...that's kind of weird.  What OS is your server running?  I've noticed that the output of some of the Vesta command line tools varies depending on the OS, so there might be improper formatting or something that I'm not properly accounting for that causing the issue.

**Comment by snakehill** [comment]
I'm running CentOS 7. If I try adding any more than 10 domains, it gives said error, regardless of the TLDs or any combination thereof (com/org/nl/care/pro/in; the only time it won't work with 10 or less is when adding the .lk domain from issue #24).
