### ISSUE TITLE
/usr/local/certbot/ doesn't exist anymore

### ISSUE THREAD

**Issue by infinitnet** [interbrite/letsencrypt-vesta#26]
In line 31 of /usr/local/bin/letsencrypt-vesta the path of the certbot has to be updated from /usr/local/certbot/certbot-auto to /usr/local/letsencrypt/certbot-auto, else the letsencrypt-vesta fails because /usr/local/certbot/ doesn't exist.

**Comment by cfgalvani** [comment]
`cd /usr/local`
`git clone https://github.com/certbot/certbot.git`
To fix it..

**Comment by jpitoniak** [comment]
Note that I changed the the installation instructions on the last update to use Certbot instead of the Let's Encrypt ACME client, as the latter has been discontinued.  As @cfgalvani pointed out, you need clone https://github.com/certbot/certbot.git when you upgrade.

**Comment by infinitnet** [comment]
Alright I see, thank you for your work.

**Comment by shahroz99** [comment]
Hello

I am trying to install this on nginx with same as your given instructions on my subdomain test.website.com but i got an error

Domain: test.website.com
   Type:   unknownHost
   Detail: No valid IP addresses found for test.website.com

So please tell me what's the solution for this.

Thanks

**Comment by mwirobruiz** [comment]
- The following errors were reported by the server:
  
  Domain: www.{my_domain}.com
  Type:   unauthorized
  Detail: Invalid response from
  http://www.{my_domain}.com/.well-known/acme-challenge/tjntdCuTWJ9Y8yV2GgnyFUeucJqfw-SfdO4NpvnUp2Y:
  "
  
  <!DOCTYPE html>
  
  <html class="" lang="en-US">
  
  <head>
  
  ```
     <meta charset="UTF-8" />
  ```
  
     <meta name="p:domain_verify" c"

To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.
Let's Encrypt returned an error status.  Aborting.

Any ideas? I did clone the certbot git as instructed.

**Comment by fmoreno-intercom2** [comment]
Excellent fix the problem
