### ISSUE TITLE
Vesta R16 removed v-list-web-domains-alias

### ISSUE THREAD

**Issue by thinkingcap** [interbrite/letsencrypt-vesta#27]
From error log

`/usr/local/bin/letsencrypt-vesta: line 64: /usr/local/vesta/bin/v-list-web-domains-alias: No such file or directory`

**Comment by cfgalvani** [comment]
@thinkingcap same problem here..

**Comment by omz187** [comment]
I got these two errors when i tried to run the command: 
/usr/local/bin/letsencrypt-vesta: line 64: /usr/local/vesta/bin/v-list-web-domains-alias: No such file or directory
/usr/local/bin/letsencrypt-vesta: line 224: /usr/local/certbot/certbot-auto: No such file or directory

If you having problems with it the way i managed to fix it was the /usr/local/certbot/ was missing which affects the v-list-web-domains-alias. (which doesn't exist anyway)

**1)** You need to re-upload the "cerbot" folder to /usr/local/certbot/ (if you cant find a copy ill send you mines as i manage to take it from a VPS which installed correctly )

**2)** Run a SSL install command Example: letsencrypt-vesta admin test.xyz (In SSH)

**3)** The error should now have changed to this:
**/usr/local/bin/letsencrypt-vesta: line 64: /usr/local/vesta/bin/v-list-web-domains-alias: No such file or directory
/usr/local/bin/letsencrypt-vesta: line 224: /usr/local/certbot/certbot-auto: Permission denied
Let's encrypt returned an error status.  Aborting.**

**4)** Go to /usr/local/certbot/ and set permissions for:
All Folders = 755 (examples of folder: .get, letshelp-certbot ,tools )
All Other files in the directory = 644 (examples of files: .pep8, Dockerfile ) 

**IMPORTANT PART**
Set these files below in that directory to = 755
certbot-auto
letsencrypt-auto
pep8.travis.sh
tox.cover.sh

5) That should fix the problem, as if fixed mines

**Comment by thinkingcap** [comment]
@cfgalvani See my PR for a fix.

**Comment by cfgalvani** [comment]
@thinkingcap I saw yesterday that vesta has Letsencrypt support via CLI now. Thank you!

**Comment by jpitoniak** [comment]
I'm looking for a solution to this.  The answer may just be to distribute a copy of the old v-list-web-domains-alias script in this project, but I need to test it before I do that.  Hopefully this was an oversight on the Vesta team's part and the script will be restored on a future update.

**Comment by jpitoniak** [comment]
I updated the script on Saturday to pull the aliases using `v-get-web-domain-value`, which should resolve this issue.

**Comment by glennharmon** [comment]
I simply had to update the script to reflect the actual location of the certbot_auto file.  It was not in the cerbot folder, but in /usr/local/letsencrypt/.
