### ISSUE TITLE
Get the following error with my Vestacp nginx + php-fpm s

### ISSUE THREAD

**Issue by kn4a-com** [interbrite/letsencrypt-vesta#33]
I tried to generate a ssl cert for one of my websites.

I used the following command:
letsencrypt-vesta admin signofkoen.nl

Got the following error

> Failed authorization procedure. www.signofkoen.nl (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://www.signofkoen.nl/.well-known/acme-challenge/TZg4pB5vQtKnGdXs735iMM9tkPdbm_-qwKON6a1Asm0: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>404 Not Found</title>
> </head><body>
> 
> <h1>Not Found</h1>
> 
> <p", signofkoen.nl (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://signofkoen.nl/.well-known/acme-challenge/oQNkROvPqkUwdap2zexRkn4QUuE0RyDkulaKVzXM3xI: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>404 Not Found</title>
> </head><body>
> 
> <h1>Not Found</h1>
> 
> <p"
> 
> IMPORTANT NOTES:
> - The following errors were reported by the server:
>   
>   Domain: www.signofkoen.nl
>   Type:   unauthorized
>   Detail: Invalid response from
>   http://www.signofkoen.nl/.well-known/acme-challenge/TZg4pB5vQtKnGdXs735iMM9tkPdbm_-qwKON6a1Asm0:
>   "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
>   <html><head>
>   <title>404 Not Found</title>
>   </head><body>
>   
>   <h1>Not Found</h1>
>   
>   <p"
>   
>   Domain: signofkoen.nl
>   Type:   unauthorized
>   Detail: Invalid response from
>   http://signofkoen.nl/.well-known/acme-challenge/oQNkROvPqkUwdap2zexRkn4QUuE0RyDkulaKVzXM3xI:
>   "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
>   <html><head>
>   <title>404 Not Found</title>
>   </head><body>
>   
>   <h1>Not Found</h1>
>   
>   <p"
>   
>   To fix these errors, please make sure that your domain name was
>   entered correctly and the DNS A record(s) for that domain
>   contain(s) the right IP address.
>   Let's Encrypt returned an error status.  Aborting.

Anyone has a clue how I could fix this?

**Comment by catsAND** [comment]
Hello. I has the same error. But https://github.com/interbrite/letsencrypt-vesta/issues/5#issuecomment-170675822 this help me. You need manual edit nginx config. I think this resolve your problem.
