### ISSUE TITLE
"Error: SSL=no doesn't exist" after install letsencrypt ssl.

### ISSUE THREAD

**Issue by willyarisky** [interbrite/letsencrypt-vesta#42]
I'm try to install letsencrypt with letsencrypt-vesta with command
letsencrypt-vesta username domain
the end of the process show this message
`Error: SSL=no doesn't exist`
3 weeks ago no error, works properly
anyone get same issue?
Thanks

**Comment by LouisForaux** [comment]
I have the same issue... Only for new certs... Renew have no problems....

**Comment by samcleathero** [comment]
This is an error caused by the latest version of Vesta changing some of the commands this tool uses - I've put a pull request in that fixes it, but if you're feeling brave you can always change the file yourself.

https://github.com/interbrite/letsencrypt-vesta/pull/40/files

**Comment by LouisForaux** [comment]
Great ! It's works ! Thanks !

**Comment by willyarisky** [comment]
Thanks ! that solved my problem.

**Comment by nesless** [comment]
Changed 2 strings as was said in https://github.com/interbrite/letsencrypt-vesta/pull/40/files

Didn't help me. :(
Still have "Error: SSL=no doesn't exist"
