### ISSUE TITLE
script stops and encrypt has some errors

### ISSUE THREAD

**Issue by voteforpresident** [interbrite/letsencrypt-vesta#6]
Everything just worked fine which you have explained in your guide.
But unfortunately the script stops and encrypt says that it has returned with an error status.

WARNING: Python 2.6 support is very experimental at present...
if you would like to work on improving it, please ensure you have backups
and then run this script again with the --debug flag!
Let's encrypt returned an error status.  Aborting.

UPDATE: I thought I had installed python 2.7 but CentOS 6.7 had only 2.6. But now everything works perfectly. Thanks.

**Comment by jpitoniak** [comment]
Glad you got it figured out.  The LE client is very picky in regards to Python versions. :)
