### ISSUE TITLE
Cert problem

### ISSUE THREAD

**Issue by voteforpresident** [interbrite/letsencrypt-vesta#9]
Everytime I try to generate a certificate I get the following error message: 

Updating letsencrypt and virtual environment dependencies.....  Could not find a version that satisfies the requirement letsencrypt (from versions: )
No matching distribution found for letsencrypt
Let's encrypt returned an error status.  Aborting.

The strange thing is that I just using a simple CentOS 7 nothing fancy.

**Comment by jpitoniak** [comment]
This sounds like an issue with the Let's Encrypt client.  You should report this to https://community.letsencrypt.org/ if you haven't already.
